# Generated by Django 2.2.2 on 2019-07-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
    ]
