# Generated by Django 2.2.2 on 2019-07-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190722_1615'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
